from .system_prompt_v1 import INTAKE_PROMPT, PARSER_INTAKE_PROMPT, DOCTOR_SYSTEM_PROMPT, FINAL_REPORT_PROMPT, TANDLANG_DETECTOR_PROMPT
from .prompt_template_v1 import DOCTOR_PROMPT_TEMPLATE, FINAL_REPORT_TEMPLATE

__all__ = ["INTAKE_PROMPT",
           "PARSER_INTAKE_PROMPT",
           "DOCTOR_SYSTEM_PROMPT",
           "DOCTOR_PROMPT_TEMPLATE",
           "FINAL_REPORT_PROMPT",
           "FINAL_REPORT_TEMPLATE",
           "TANDLANG_DETECTOR_PROMPT"]